[[redirects]]
  from = "/api/admin/adminlogin"
  to = "https://mobyletech.herokuapp.com/api/admin/adminlogin"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/admin"
  to = "https://mobyletech.herokuapp.com/api/admin"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}